server:
    port: 9000
spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: password
        #url: jdbc:mysql://fyp-db/fyp
        username: root
        url: jdbc:mysql://localhost:3306/fyp
    h2:
        console:
            enabled: true
            path: /h2
    jpa:
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                format_sql: true
        show-sql: true
    cache:
        redis:
            cache-null-values: true
        type: redis

myredisconfig:
    host: fyp-redis
    port: 6379
    time-to-live: 6000S