server:
    port: 9000
spring:

    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: password
        url: jdbc:mysql://localhost:3306/FYP
        username: root
    h2:
        console:
            enabled: true
            path: /h2
    jpa:
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                format_sql: true
        show-sql: true
    cache:
        redis:
            cache-null-values: true
        type: redis
myredisconfig:
    host: localhost
    port: 6379
    time-to-live: 60S